### ISSUE TITLE
missing "Domain" project

### ISSUE THREAD

**Issue by Shawn-Fan** [brainwipe/BrighterOnAspNetCoreExample#1]
The problem is that the "Domain" project is missing but it can be set up by following your blog https://brainwipe.github.io/asp.net/core/brighter/cqrs/2017/10/04/brighter-on-aspnetcore/

Thanks for your awesome sample project!

Shawn

**Comment by brainwipe** [comment]
Thank you! I think I've fallen foul of creating a project in the default Visual Studio folder rather than in the solution folder. Then when I checked in, it didn't include the Domain project. Perhaps the worst case of "It works on my machine".
